Resources:
                          
  AppSyncLambdaServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Lambda-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                 
                  - "appsync.amazonaws.com"
                  
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "Lambda-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"

  

                  Resource:
                    - "arn:aws:lambda:us-east-2:${self:custom.accountId}:function:${self:service}-dev-graphql"
                    - "arn:aws:lambda:use-east-2:${self:custom.accountId}:function:${self:service}-dev-graphql:*"
 
                                
